services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: typeshi
      POSTGRES_PASSWORD: typeshi
      POSTGRES_DB: typeshi
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
